export const COMMENTS_REQUEST = "COMMENTS_REQUEST";
export const COMMENTS_FAILED = "COMMENTS_FAILED";
export const COMMENTS_SUCCESS = "COMMENTS_SUCCESS";

export const COMMENT_CREATE_REQUEST = "COMMENT_CREATE_REQUEST";
export const COMMENT_CREATE_SUCCESS = "COMMENT_CREATE_SUCCESS";
export const COMMENT_CREATE_FAILED = "COMMENT_CREATE_FAILED";
