export const POST_LIST_REQUEST = "POST_LIST_REQUEST";
export const POST_LIST_FAILED = "POST_LIST_FAILED";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";

export const POST_DETAILS_REQUEST = "POST_DETAILS_REQUEST";
export const POST_DETAILS_SUCCESS = "POST_DETAILS_SUCCESS";
export const POST_DETAILS_FAILED = "POST_DETAILS_FAILED";
export const POST_DETAILS_RESET = "POST_DETAILS_RESET";

export const POST_EDIT_REQUEST = "POST_EDIT_REQUEST";
export const POST_EDIT_SUCCESS = "POST_EDIT_SUCCESS";
export const POST_EDIT_FAILED = "POST_EDIT_FAILED";
export const POST_EDIT_RESET = "POST_EDIT_RESET";

export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAILED = "POST_CREATE_FAILED";
export const POST_CREATE_RESET = "POST_CREATE_RESET";
